org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8 -Duser.home=/home/kingfish600/workspace/tools/gradle-home/home
android.aapt2FromMavenOverride=/home/kingfish600/workspace/tools/sdk/build-tools/34.0.0/aapt2
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
